import type { Metadata } from 'next';

import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

import '@/styles/global.scss';

export const metadata: Metadata = {
    title: 'Chen Lin Chu Portfolio',
    description: 'Generated by Chen Lin Chu'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />

                {children}

                <Footer />
            </body>
        </html>
    );
}
